### PR TITLE
Master

### PR DESCRIPTION
**Pull request by BluesBoyJin**
resolve compilation error; improve INSTALL.md

### CODE REVIEW

**Comment by heshuchao** [comment]
The <mutex> header file missing  cause no compilation  error when build in ubuntu20.04,  but in ubuntu22.04 ,  the compilation process will report an error and terminate .
After adding the missing header file, No error was reported during the compilation process, and the node binary  runs properly both in ubuntu 20.04 and 22.04 with a simple test.
